name: coverage
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run build
      - run: npm run coverage
      - uses: codecov/codecov-action@v5
